jenkins:  http://0.0.0.0:8080/
repo: file:///Users/benji/cuttlesoft/flask-bitmapist
template: templates
namefmt: '{shortref}'
overwrite: true

build-on-create: true
enable: true

ignore:
  - 'refs/heads/feature/.*'

refs:
  - 'refs/heads/master/.*'
  - 'refs/heads/release/.*'
  - 'refs/heads/development/.*'
  - 'refs/heads/stable/.*'
